import './app.css';
import { AuthProvider } from './Providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider Children={children} />
      </body>
    </html>
  );
}
